### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Song367** [AIFSH/CosyVoice-ComfyUI#10]
input frame rate=50
 [ 0 ; 9 3 m 2 0 2 4 - 0 7 - 1 4   2 2 : 5 1 : 3 0 . 7 4 7 3 3 9 1   [ W : o n n x r u n t i m e : ,   t r a n s f o r m e r _ m e m c p y . c c : 7 4   o n n x r u n t i m e : : M e m c p y T r a n s f o r m e r : : A p p l y I m p l ]   1 2   M e m c p y   n o d e s   a r e   a d d e d   t o   t h e   g r a p h   m a i n _ g r a p h   f o r   C U D A E x e c u t i o n P r o v i d e r .   I t   m i g h t   h a v e   n e g a t i v e   i m p a c t   o n   p e r f o r m a n c e   ( i n c l u d i n g   u n a b l e   t o   r u n   C U D A   g r a p h ) .   S e t   s e s s i o n _ o p t i o n s . l o g _ s e v e r i t y _ l e v e l = 1   t o   s e e   t h e   d e t a i l   l o g s   b e f o r e   t h i s   m e s s a g e .  [ m 
  [ 0 ; 9 3 m 2 0 2 4 - 0 7 - 1 4   2 2 : 5 1 : 3 0 . 7 5 0 0 9 1 9   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 1 6 6   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   S o m e   n o d e s   w e r e   n o t   a s s i g n e d   t o   t h e   p r e f e r r e d   e x e c u t i o n   p r o v i d e r s   w h i c h   m a y   o r   m a y   n o t   h a v e   a n   n e g a t i v e   i m p a c t   o n   p e r f o r m a n c e .   e . g .   O R T   e x p l i c i t l y   a s s i g n s   s h a p e   r e l a t e d   o p s   t o   C P U   t o   i m p r o v e   p e r f .  [ m 
  [ 0 ; 9 3 m 2 0 2 4 - 0 7 - 1 4   2 2 : 5 1 : 3 0 . 7 5 0 2 7 2 5   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 1 6 8   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   R e r u n n i n g   w i t h   v e r b o s e   o u t p u t   o n   a   n o n - m i n i m a l   b u i l d   w i l l   s h o w   n o d e   a s s i g n m e n t s .  [ m 
 !!! Exception during processing!!! string indices must be integers
Traceback (most recent call last):
  File "E:\workplace\svd_comfyui\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\workplace\svd_comfyui\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\workplace\svd_comfyui\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\workplace\svd_comfyui\custom_nodes\CosyVoice-ComfyUI\nodes.py", line 108, in generate
    waveform = prompt_wav['waveform'].squeeze(0)
TypeError: string indices must be integers

Prompt executed in 242.86 seconds

![image](https://github.com/user-attachments/assets/8845737c-0069-46ac-800b-879bf294de85)

**Comment by AIFSH** [comment]
update ComfyUI and use ComfyUI native audioloader
