### ISSUE TITLE
 在"A绘世启动器"2.8.5中报这个错误,怎么解决

### ISSUE THREAD

**Issue by piexl** [AIFSH/CosyVoice-ComfyUI#12]
![image](https://github.com/user-attachments/assets/98de965b-352c-4cde-b7ae-fddade323574)
  DEPRECATION: webrtcvad is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for webrtcvad ...   error: subprocess-exited-with-error

  × Running setup.py install for webrtcvad did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> webrtcvad

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

在"A绘世启动器"2.8.5中报这个错误,怎么解决

**Comment by moddz** [comment]
same

**Comment by hillleaf** [comment]
搜索 安装 webrtcvad 失败，有2篇 csdn 上的文章 有讲解，就是 你要 安装 C++ 14版本以上的编译器。

**Comment by piexl** [comment]
> 搜索 安装 webrtcvad 失败，有2篇 csdn 上的文章 有讲解，就是 你要 安装 C++ 14版本以上的编译器。

确实是这个问题，我重新安装了vc++,重启电脑,再运行就按照好了,安装包地址
通过百度网盘分享的文件：
链接：https://pan.baidu.com/s/1j8yapGz3rToDHvFZ-K3pKQ?pwd=fj0r 
提取码：fj0r

**Comment by piexl** [comment]
已经解决
