### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by haomole** [AIFSH/CosyVoice-ComfyUI#16]
![image](https://github.com/user-attachments/assets/4d7de539-ef3e-4193-a4cd-1259eace775b)

**Comment by AIFSH** [comment]
need ffmpeg

**Comment by haomole** [comment]
![03b79f6549e356816ac6104ff17fac08](https://github.com/user-attachments/assets/d4547ce0-bd15-4f67-befa-42b9efae0c3c)
Now the error

**Comment by haomole** [comment]
Restart your computer
