### ISSUE TITLE
Comfy Can't Load These Nodes

### ISSUE THREAD

**Issue by AtomicPerception** [AIFSH/CosyVoice-ComfyUI#28]
I add the nodes and try the example workflows and they come up broken.

Tried several times.
Stuff is broken...

**Comment by Awhwah** [comment]
I'm getting the same issues here as well. I've tried installing manually with the directions provided here on git, as well as just installing directly with ComfyUI Manager. No such luck. 
![comfy](https://github.com/user-attachments/assets/fd5df127-7f14-405e-9dd3-f0b26e0f2645)

**Comment by konradre** [comment]
Yup, same here.

**Comment by AtomicPerception** [comment]
I finally got everything to work.

**Try this first...(supply the path to your Comfy install.**
S:\ComfyUI_Portable\python_embeded\python.exe -m pip install conformer audiosegment srt modelscope -U

**Then make sure your FFMPEG is correctly installed. Mine was hosed. It's important that you have ffmpeg-python installed and not python-ffmpeg.**

**This should remove all your FFMPEG references and install the correct one.**
S:\ComfyUI_Portable\python_embeded\python.exe -m pip uninstall ffmpeg
S:\ComfyUI_Portable\python_embeded\python.exe -m pip uninstall ffmpeg-python
S:\ComfyUI_Portable\python_embeded\python.exe -m pip uninstall python-ffmpeg
S:\ComfyUI_Portable\python_embeded\python.exe -m pip install ffmpeg-python

**Finally install the missing wheels.**
S:\ComfyUI_Portable\python_embeded\python.exe -m pip install webrtcvad-wheels

**Comment by konradre** [comment]
What would the non-portable version of this be? Im running 2 venvs and want to do this in the second one to avoid dependency conflicts.
