### ISSUE TITLE
how to run this?

### ISSUE THREAD

**Issue by loca1first** [AIFSH/CosyVoice-ComfyUI#4]
i get this after installing pip requirements but not sure what to do next? also can you please make one for sensevoice?

ning, lightning
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.9.0
    Uninstalling typing_extensions-4.9.0:
      Successfully uninstalled typing_extensions-4.9.0
  Attempting uninstall: ruamel.yaml.clib
    Found existing installation: ruamel.yaml.clib 0.2.6
    Uninstalling ruamel.yaml.clib-0.2.6:
      Successfully uninstalled ruamel.yaml.clib-0.2.6
  Attempting uninstall: ruamel.yaml
    Found existing installation: ruamel.yaml 0.17.21
    Uninstalling ruamel.yaml-0.17.21:
      Successfully uninstalled ruamel.yaml-0.17.21
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda 23.9.0 requires ruamel-yaml<0.18,>=0.11.14, but you have ruamel-yaml 0.18.6 which is incompatible.
Successfully installed HyperPyYAML-1.2.2 absl-py-2.1.0 aiohttp-3.9.5 aiosignal-1.3.1 annotated-types-0.7.0 antlr4-python3-runtime-4.9.3 async-timeout-4.0.3 audioread-3.0.1 coloredlogs-15.0.1 conformer-0.3.2 contourpy-1.2.1 cycler-0.12.1 deepspeed-0.14.4 diffusers-0.29.2 einops-0.8.0 flatbuffers-24.3.25 fonttools-4.53.1 frozenlist-1.4.1 gdown-5.2.0 grpcio-1.65.0 grpcio-tools-1.65.0 hjson-3.1.0 huggingface-hub-0.23.4 humanfriendly-10.0 hydra-core-1.3.2 importlib-metadata-8.0.0 inflect-7.3.1 jieba-0.42.1 joblib-1.4.2 kiwisolver-1.4.5 lazy-loader-0.4 librosa-0.10.2.post1 lightning-2.3.3 lightning-utilities-0.11.3.post0 llvmlite-0.43.0 markdown-3.6 markdown-it-py-3.0.0 matplotlib-3.9.1 mdurl-0.1.2 modelscope-1.16.0 msgpack-1.0.8 multidict-6.0.5 ninja-1.11.1.1 numba-0.60.0 nvidia-ml-py-12.555.43 omegaconf-2.3.0 onnxruntime-gpu-1.18.1 openai-whisper-20231117 pooch-1.8.2 protobuf-5.27.2 py-cpuinfo-9.0.0 pyarrow-16.1.0 pydantic-2.8.2 pydantic-core-2.20.1 pyparsing-3.1.2 pypinyin-0.51.0 pytorch-lightning-2.3.3 regex-2024.5.15 rich-13.7.1 ruamel.yaml-0.18.6 ruamel.yaml.clib-0.2.8 safetensors-0.4.3 scikit-learn-1.5.1 scipy-1.14.0 soundfile-0.12.1 soxr-0.3.7 tensorboard-2.16.2 tensorboard-data-server-0.7.2 threadpoolctl-3.5.0 tiktoken-0.7.0 torchmetrics-1.4.0.post0 typeguard-4.3.0 typing-extensions-4.12.2 werkzeug-3.0.3 wget-3.2 yarl-1.9.4 zipp-3.19.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by spxneo** [comment]
just ran python nodes.py and nothing happened

**Comment by AIFSH** [comment]
why not readme？sensevoice-ComfyUI has been pushed
