### ISSUE TITLE
3s克隆，文本太长后会缺失一段语音，感觉被分成了多句，但是只剩最后一句

### ISSUE THREAD

**Issue by aijuncheng** [AIFSH/CosyVoice-ComfyUI#42]
语音合成文本：“砰，砰，砰！就在这时，房门被大力拍响，萧凡脸色一变。刘坤那家伙莫不是有同党？拿上甩棍萧凡到门口，他通过猫眼往外面瞅了瞅。”
但是将标点符号去除部分后，即可正常合成语音如："砰，砰，砰！就在这时房门被大力拍响，萧凡脸色一变刘坤那家伙莫不是有同党拿上甩棍萧凡到门口，他通过猫眼往外面瞅了瞅。"

**Comment by PredatorMan** [comment]
用了一段时间之后，莫名的只生成后面一句话的语音

**Comment by leegang** [comment]
是的 新版本有这个问题，之前版本没有

**Comment by AIFSH** [comment]
fixed，update your code
