### ISSUE TITLE
Solve the issue of unable to download automatically.

### ISSUE THREAD

**Issue by cardenluo** [AIFSH/CosyVoice-ComfyUI#5]
①update function code as below:
②put the model :
![image](https://github.com/user-attachments/assets/6dcd4187-223a-4b9d-a830-2a412aaf40ab)

def generate(self, tts_text, inference_mode, sft_dropdown, seed,
             prompt_text=None, prompt_wav=None, instruct_text=None):
    if inference_mode == '自然语言控制':
        model_dir = os.path.join(pretrained_models, "CosyVoice-300M-Instruct")
        snapshot_download(model_id="iic/CosyVoice-300M-Instruct")
        assert instruct_text is not None, "in 自然语言控制 mode, instruct_text can't be none"

    if inference_mode in ["跨语种复刻", '3s极速复刻']:
        model_dir = os.path.join(pretrained_models, "CosyVoice-300M")
        snapshot_download(model_id="iic/CosyVoice-300M")
        assert prompt_wav is not None, "in 跨语种复刻 or 3s极速复刻 mode, prompt_wav can't be none"
        if inference_mode == "3s极速复刻":
            assert len(prompt_text) > 0, "prompt文本为空，您是否忘记输入prompt文本？"

    if inference_mode == "预训练音色":
        model_dir = os.path.join(pretrained_models, "CosyVoice-300M-SFT")
        snapshot_download(model_id="iic/CosyVoice-300M-Instruct")

    if self.model_dir != model_dir:
        self.model_dir = model_dir
        self.cosyvoice = CosyVoice(model_dir)

    if prompt_wav:
        waveform = prompt_wav['waveform'].squeeze(0)
        source_sr = prompt_wav['sample_rate']
        speech = waveform.mean(dim=0, keepdim=True)
        if source_sr != prompt_sr:
            speech = torchaudio.transforms.Resample(orig_freq=source_sr, new_freq=prompt_sr)(speech)

    if inference_mode == '预训练音色':
        print('get sft inference request')
        print(self.model_dir)
        set_all_random_seed(seed)
        output = self.cosyvoice.inference_sft(tts_text, sft_dropdown)
    elif inference_mode == '3s极速复刻':
        print('get zero_shot inference request')
        print(self.model_dir)
        prompt_speech_16k = postprocess(speech)
        set_all_random_seed(seed)
        output = self.cosyvoice.inference_zero_shot(tts_text, prompt_text, prompt_speech_16k)
    elif inference_mode == '跨语种复刻':
        print('get cross_lingual inference request')
        print(self.model_dir)
        prompt_speech_16k = postprocess(speech)
        set_all_random_seed(seed)
        output = self.cosyvoice.inference_cross_lingual(tts_text, prompt_speech_16k)
    else:
        print('get instruct inference request')
        set_all_random_seed(seed)
        print(self.model_dir)
        output = self.cosyvoice.inference_instruct(tts_text, sft_dropdown, instruct_text)

    audio = {"waveform": [output['tts_speech']], "sample_rate": target_sr}
    return (audio,)

**Comment by killpj** [comment]
I just encountered this issue, and although it’s resolved, the CosyVoice-300M-Instruct model is still being downloaded to .cache/modelscope/hub/iic and cannot be deleted, otherwise it will be re-downloaded.

**Comment by AIFSH** [comment]
update modelscope！
