### ISSUE TITLE
english language?

### ISSUE THREAD

**Issue by shivshankar11** [AIFSH/CosyVoice-ComfyUI#8]
english language?

**Comment by ekswathi** [comment]
it is working with english language, but user interface is in not

**Comment by shivshankar11** [comment]
Why all input node are required? If cloning is not used then audio input should not be required. Instructions input should not be mandatory.

**Comment by ekswathi** [comment]
you don't need all inputs together always. it is up to how you want the output. you can try the sample workflows.
